name: ghosten_player
description: "Ghosten Player: A Video Player"
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 2.0.0-alpha.0
environment:
  sdk: ^3.6.1
dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: any
  animations: ^2.0.0
  api:
    path: packages/api
  bluetooth:
    path: packages/bluetooth
  cached_network_image: ^3.4.0
  collection: ^1.19.0
  date_format: ^2.0.0
  dio: ^5.7.0
  file_picker:
    path: packages/file_picker
  flutter_bloc: ^9.1.0
  flutter_markdown: ^0.7.0
  flutter_slidable: ^4.0.0
  flutter_spinkit: ^5.2.0
  infinite_scroll_pagination: ^4.1.0
  install_plugin: ^2.1.0
  photo_view: ^0.15.0
  provider: ^6.1.4
  qr_flutter: ^4.1.0
  readmore: ^3.0.0
  rxdart: ^0.28.0
  scaled_app: ^2.3.0
  screen_brightness: ^2.1.0
  shared_preferences: ^2.5.0
  shimmer: ^3.0.0
  smooth_page_indicator: ^1.2.0
  url_launcher: ^6.3.0
  video_player:
    path: packages/video_player
  volume_controller: ^3.2.0
  webview_cookie_manager: ^2.0.0
  webview_flutter: ^4.10.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/common/images/
    - path: assets/tv/images/
      flavors:
        - tv
  fonts:
    - family: Roboto Condensed
      fonts:
        - asset: fonts/RobotoCondensed-Regular.ttf
