name: ghosten_player
description: "Ghosten Player: A Video Player"
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 0.0.0
environment:
  sdk: ^3.7.2
dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: any
  animations: ^2.1.1
  api:
    git:
      url: https://github.com/GhostenEditor/Ghosten-Player-flutter-packages.git
      path: api
      ref: v0.0.2
  bluetooth:
    git:
      url: https://github.com/GhostenEditor/Ghosten-Player-flutter-packages.git
      path: bluetooth
      ref: v0.0.2
  cached_network_image: ^3.4.0
  collection: ^1.19.0
  date_format: ^2.0.0
  dio: ^5.9.1
  dio_cache_interceptor: ^4.0.5
  file_picker:
    git:
      url: https://github.com/GhostenEditor/Ghosten-Player-flutter-packages.git
      path: file_picker
      ref: v0.0.2
  flutter_archive: ^6.0.4
  flutter_bloc: ^9.1.0
  flutter_slidable: ^4.0.3
  flutter_spinkit: ^5.2.2
  flutter_widget_from_html_core: ^0.15.2
  html: ^0.15.4
  infinite_scroll_pagination: ^5.1.1
  install_plugin: ^2.1.0
  markdown: ^7.2.0
  markdown_widget:
    git:
      url: https://github.com/GhostenEditor/markdown_widget.git
      ref: master
  photo_view: ^0.15.0
  provider: ^6.1.5+1
  qr_flutter: ^4.1.0
  readmore: ^3.0.0
  rxdart: ^0.28.0
  scaled_app: ^2.3.0
  screen_brightness: ^2.1.7
  scroll_to_index: ^3.0.1
  shared_preferences: ^2.5.3
  shimmer: ^3.0.0
  smooth_page_indicator: ^2.0.1
  url_launcher: ^6.3.2
  video_player:
    git:
      url: https://github.com/GhostenEditor/Ghosten-Player-flutter-packages.git
      path: video_player
      ref: v0.0.2
  volume_controller: ^3.4.1
  webview_cookie_manager_plus: ^2.0.17
  webview_flutter: ^4.13.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/common/images/
    - path: assets/tv/images/
      flavors:
        - tv
  fonts:
    - family: Roboto Condensed
      fonts:
        - asset: fonts/RobotoCondensed-Regular.ttf
