name: ghosten_player
description: "Ghosten Player: A Video Player"
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.4.0
environment:
  sdk: '>=3.4.3 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: any
  animations: ^2.0.11
  api:
    path: packages/api
  bluetooth:
    path: packages/bluetooth
  cached_network_image: ^3.4.1
  collection: ^1.18.0
  date_format: ^2.0.9
  dio: ^5.7.0
  file_picker:
    path: packages/file_picker
  flutter_markdown: ^0.7.4
  flutter_slidable: ^3.1.2
  flutter_spinkit: ^5.2.1
  infinite_scroll_pagination: ^4.1.0
  install_plugin: ^2.1.0
  player_view:
    path: packages/player_view
  photo_view: ^0.15.0
  provider: ^6.1.2
  qr_flutter: ^4.1.0
  rxdart: ^0.28.0
  scaled_app: ^2.3.0
  shared_preferences: ^2.5.1
  url_launcher: ^6.3.1
  webview_cookie_manager: ^2.0.6
  webview_flutter: ^4.8.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/images/
  fonts:
    - family: Roboto Condensed
      fonts:
        - asset: fonts/RobotoCondensed-Regular.ttf



